import type { Metadata } from "next";
import { Geist, Geist_Mono } from 'next/font/google';
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";
import Header from "@/components/header"; // Added Header import
import { AuthProvider } from '@/hooks/useAuth'; // Import AuthProvider

// Fonts
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
});

// Metadata
export const metadata: Metadata = {
  title: "Job Application Advisor",
  description: "Generated by louAI",
  metadataBase: new URL("https://job-application-advisor.vercel.app/"),
  openGraph: {
    title: "Job Application Advisor",
    description: "An AI-powered job application assistant by louAI",
    url: "https://job-application-advisor.vercel.app/",
    siteName: "Job Application Advisor",
    locale: "en_US",
    type: "website",
  },
};

// Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black flex flex-col h-screen overflow-hidden`}
      >
        <AuthProvider> {/* Wrap with AuthProvider */}
          {/* Header with profile */}
          <Header />
          
          {/* Main content */}
          <main className="flex-1 overflow-hidden">
            {children}
          </main>
          
          <GoogleAnalytics gaId="G-GYSTWLYX1T" />
        </AuthProvider> {/* Close AuthProvider */}
      </body>
    </html>
  );
}